// ---- Telegram customer notifications ----
// Messages a customer's linked Telegram account when their order status
// changes (approved/rejected) or they win a raffle. This is a different use
// of TELEGRAM_BOT_TOKEN than verifyTelegramInitData in utils.js - that only
// verifies Mini App launches came from Telegram; this actually calls
// Telegram's Bot API to push a message out.
//
// The link between "this order" and "this Telegram chat" is the phone
// number: upsertTelegramUser (db.js) records {telegramId, phone, ...} the
// moment someone shares their contact with the bot, via POST /telegram/link
// in routes/public.js. sendMessage's chat_id can be that same numeric
// telegramId directly, because Telegram treats a bot's chat with a user who
// has started/messaged it as chat_id == user_id - no separate "chat id"
// needs to be tracked.
//
// Best-effort by design, same philosophy as alerts.js: a buyer who never
// linked Telegram (still the common case - it's optional) or who has
// blocked the bot must never cause the admin action that triggered the
// message (approve/reject/draw) to fail or even slow down. notifyCustomer
// swallows every failure itself so callers can fire-and-forget it after
// already sending their HTTP response, exactly like reportLockout in
// alerts.js is called without awaiting it.

const TELEGRAM_API_BASE = 'https://api.telegram.org';

function isConfigured() {
  return Boolean(process.env.TELEGRAM_BOT_TOKEN);
}

/**
 * Low-level send via Telegram's Bot API. Throws on missing config or a
 * non-ok response (e.g. 403 = user blocked the bot, 400 = chat not found) -
 * mirrors sendMail() in alerts.js, which also throws and leaves it to the
 * caller to decide whether a failure should be best-effort (swallowed) or
 * surfaced. notifyCustomer() below is the best-effort caller for this file;
 * nothing here needs the surfaced-error path today, but it's exported in
 * case a future caller wants the message to genuinely have to succeed.
 *
 * No parse_mode is set (plain text) - order data going into these messages
 * (raffle titles, rejection reasons) is admin-authored, not attacker
 * input, but plain text sidesteps ever having to think about escaping for
 * Telegram's HTML/Markdown parsers entirely.
 */
async function sendTelegramMessage(chatId, text) {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  if (!token) throw new Error('TELEGRAM_BOT_TOKEN is not set');

  const res = await fetch(`${TELEGRAM_API_BASE}/bot${token}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ chat_id: chatId, text, disable_web_page_preview: true })
  });

  const body = await res.json().catch(() => null);
  if (!res.ok || !body || body.ok !== true) {
    const detail = (body && body.description) || res.statusText;
    throw new Error(`Telegram sendMessage failed (${res.status}): ${detail}`);
  }
  return body.result;
}

/**
 * Look up the Telegram account linked to an order's phone number and send
 * it a message. Never throws:
 *   - no TELEGRAM_BOT_TOKEN configured -> silent no-op (feature is optional)
 *   - phone was never linked to a Telegram account -> silent no-op (the
 *     normal case for anyone who didn't come in through the bot)
 *   - the send itself fails -> logged, not thrown
 * so every call site can fire this off after responding to the HTTP
 * request without a try/catch or .catch() of its own.
 *
 * @param {object} data - loaded db data (needs .telegramUsers)
 * @param {object} order - the order to notify about; must have `.phone`
 * @param {string} text - message body
 */
async function notifyCustomer(data, order, text) {
  try {
    if (!isConfigured()) return;
    const link = (data.telegramUsers || []).find(u => u.phone === order.phone);
    if (!link) return; // this buyer never shared their phone with the bot
    await sendTelegramMessage(link.telegramId, text);
  } catch (err) {
    console.error(`[telegram] Failed to notify order ${order.id} (phone ${order.phone}):`, err.message);
  }
}

/**
 * Resolve a Telegram @username to a numeric chat id, so the admin only
 * ever has to type the handle they already know rather than hunting down
 * an internal id. There is no Bot API call that goes "username -> chat
 * id" directly (sendMessage's chat_id accepts "@name" only for public
 * channels, never for a private user chat) - the only way a bot can learn
 * a user's chat id is from an update that user generated by messaging the
 * bot. getUpdates (long-poll style, no webhook required) returns the
 * last batch of those; this scans them for a message whose sender's
 * username matches, newest first, and returns that chat id.
 *
 * This only sees messages sent to the bot since Telegram last delivered
 * them elsewhere (getUpdates consumes its queue), so the admin has to
 * message the bot *before* clicking "Link Telegram" in Settings - the UI
 * copy says as much. Returns null (never throws) if nothing matches, so
 * the route can turn that into a friendly "we didn't see a message from
 * that username yet" instead of a 500.
 *
 * @param {string} username - without the leading '@', case-insensitive
 * @returns {Promise<string|null>} chat id as a string, or null
 */
async function findChatIdByUsername(username) {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  if (!token) throw new Error('TELEGRAM_BOT_TOKEN is not set');
  if (!username) return null;
  const target = username.replace(/^@/, '').toLowerCase();

  const res = await fetch(`${TELEGRAM_API_BASE}/bot${token}/getUpdates?limit=100`);
  const body = await res.json().catch(() => null);
  if (!res.ok || !body || body.ok !== true || !Array.isArray(body.result)) {
    throw new Error(`Telegram getUpdates failed (${res.status}): ${(body && body.description) || res.statusText}`);
  }

  // Newest first: last() before first(), so a re-share/newer message from
  // the right person wins over a stale one still sitting in the batch.
  for (let i = body.result.length - 1; i >= 0; i--) {
    const msg = body.result[i].message || body.result[i].edited_message;
    const from = msg && msg.from;
    if (from && from.username && from.username.toLowerCase() === target) {
      return String(msg.chat.id);
    }
  }
  return null;
}

/**
 * Push a DM to every admin who has linked a Telegram chat id (see
 * findChatIdByUsername / POST /api/admin/telegram/link-account). Same
 * best-effort contract as notifyCustomer: never throws, so callers can
 * fire this off after already responding to the HTTP request. Each
 * admin's send is wrapped individually so one admin's blocked bot / bad
 * chat id can't stop the others from being notified.
 *
 * @param {object} data - loaded db data (needs .admins)
 * @param {string} text - message body
 */
async function notifyAdmin(data, text) {
  if (!isConfigured()) return;
  const targets = (data.admins || []).filter(a => a.telegramChatId);
  for (const admin of targets) {
    try {
      await sendTelegramMessage(admin.telegramChatId, text);
    } catch (err) {
      console.error(`[telegram] Failed to notify admin ${admin.username}:`, err.message);
    }
  }
}

module.exports = { sendTelegramMessage, notifyCustomer, notifyAdmin, findChatIdByUsername, isConfigured };
